/**
 * Language definitions for the application
 * Each language has a code, name, and flag emoji
 */
export const LANGUAGES = {
  en: { name: 'English', flag: '🇺🇸' },
  zh_cn: { name: '中文', flag: '🇨🇳' }, // Mandarin 
  es: { name: 'Español', flag: '🇪🇸' },
  fr: { name: 'Français', flag: '🇫🇷' },
  pt: { name: 'Português', flag: '🇵🇹' },
  ru: { name: 'Русский', flag: '🇷🇺' },
  id: { name: 'Bahasa Indonesia', flag: '🇮🇩' },
  de: { name: 'Deutsch', flag: '🇩🇪' },
  ja: { name: '日本語', flag: '🇯🇵' },
  tr: { name: 'Türkçe', flag: '🇹🇷' },
  zh_hk: { name: '廣東話', flag: '🇭🇰' }, // Cantonese
  vi: { name: 'Tiếng Việt', flag: '🇻🇳' },
  ko: { name: '한국어', flag: '🇰🇷' },
  it: { name: 'Italiano', flag: '🇮🇹' },
  th: { name: 'ภาษาไทย', flag: '🇹🇭' },
  hi: { name: 'हिन्दी', flag: '🇮🇳' },
  ur: { name: 'اردو', flag: '🇵🇰' },
  ar: { name: 'العربية', flag: '🇸🇦' },
};

// Matrix of language names in each language
export const LANGUAGE_NAMES = {
  en: {
    en: 'English',
    zh_cn: '英语',
    es: 'Inglés',
    fr: 'Anglais',
    pt: 'Inglês',
    ru: 'Английский',
    id: 'Bahasa Inggris',
    de: 'Englisch',
    ja: '英語',
    tr: 'İngilizce',
    zh_hk: '英文',
    vi: 'Tiếng Anh',
    ko: '영어',
    it: 'Inglese',
    th: 'ภาษาอังกฤษ',
    hi: 'अंग्रेज़ी',
    ur: 'انگریزی',
    ar: 'الإنجليزية'
  },
  zh_cn: {
    en: 'Mandarin Chinese',
    zh_cn: '中文',
    es: 'Chino Mandarín',
    fr: 'Chinois Mandarin',
    pt: 'Chinês Mandarim',
    ru: 'Китайский',
    id: 'Bahasa Mandarin',
    de: 'Mandarin',
    ja: '中国語',
    tr: 'Mandarin Çincesi',
    zh_hk: '普通話',
    vi: 'Tiếng Trung',
    ko: '중국어',
    it: 'Cinese Mandarino',
    th: 'ภาษาจีนกลาง',
    hi: 'मैंडरिन चीनी',
    ur: 'مینڈرن چینی',
    ar: 'الصينية الماندرين'
  },
  es: {
    en: 'Spanish',
    zh_cn: '西班牙语',
    es: 'Español',
    fr: 'Espagnol',
    pt: 'Espanhol',
    ru: 'Испанский',
    id: 'Bahasa Spanyol',
    de: 'Spanisch',
    ja: 'スペイン語',
    tr: 'İspanyolca',
    zh_hk: '西班牙文',
    vi: 'Tiếng Tây Ban Nha',
    ko: '스페인어',
    it: 'Spagnolo',
    th: 'ภาษาสเปน',
    hi: 'स्पैनिश',
    ur: 'ہسپانوی',
    ar: 'الإسبانية'
  },
  fr: {
    en: 'French',
    zh_cn: '法语',
    es: 'Francés',
    fr: 'Français',
    pt: 'Francês',
    ru: 'Французский',
    id: 'Bahasa Prancis',
    de: 'Französisch',
    ja: 'フランス語',
    tr: 'Fransızca',
    zh_hk: '法文',
    vi: 'Tiếng Pháp',
    ko: '프랑스어',
    it: 'Francese',
    th: 'ภาษาฝรั่งเศส',
    hi: 'फ्रेंच',
    ur: 'فرانسیسی',
    ar: 'الفرنسية'
  },
  pt: {
    en: 'Portuguese',
    zh_cn: '葡萄牙语',
    es: 'Portugués',
    fr: 'Portugais',
    pt: 'Português',
    ru: 'Португальский',
    id: 'Bahasa Portugis',
    de: 'Portugiesisch',
    ja: 'ポルトガル語',
    tr: 'Portekizce',
    zh_hk: '葡萄牙文',
    vi: 'Tiếng Bồ Đào Nha',
    ko: '포르투갈어',
    it: 'Portoghese',
    th: 'ภาษาโปรตุเกส',
    hi: 'पुर्तगाली',
    ur: 'پرتگالی',
    ar: 'البرتغالية'
  },
  ru: {
    en: 'Russian',
    zh_cn: '俄语',
    es: 'Ruso',
    fr: 'Russe',
    pt: 'Russo',
    ru: 'Русский',
    id: 'Bahasa Rusia',
    de: 'Russisch',
    ja: 'ロシア語',
    tr: 'Rusça',
    zh_hk: '俄文',
    vi: 'Tiếng Nga',
    ko: '러시아어',
    it: 'Russo',
    th: 'ภาษารัสเซีย',
    hi: 'रूसी',
    ur: 'روسی',
    ar: 'الروسية'
  },
  id: {
    en: 'Indonesian',
    zh_cn: '印尼语',
    es: 'Indonesio',
    fr: 'Indonésien',
    pt: 'Indonésio',
    ru: 'Индонезийский',
    id: 'Bahasa Indonesia',
    de: 'Indonesisch',
    ja: 'インドネシア語',
    tr: 'Endonezce',
    zh_hk: '印尼文',
    vi: 'Tiếng Indonesia',
    ko: '인도네시아어',
    it: 'Indonesiano',
    th: 'ภาษาอินโดนีเซีย',
    hi: 'इंडोनेशियाई',
    ur: 'انڈونیشی',
    ar: 'الإندونيسية'
  },
  de: {
    en: 'German',
    zh_cn: '德语',
    es: 'Alemán',
    fr: 'Allemand',
    pt: 'Alemão',
    ru: 'Немецкий',
    id: 'Bahasa Jerman',
    de: 'Deutsch',
    ja: 'ドイツ語',
    tr: 'Almanca',
    zh_hk: '德文',
    vi: 'Tiếng Đức',
    ko: '독일어',
    it: 'Tedesco',
    th: 'ภาษาเยอรมัน',
    hi: 'जर्मन',
    ur: 'جرمن',
    ar: 'الألمانية'
  },
  ja: {
    en: 'Japanese',
    zh_cn: '日语',
    es: 'Japonés',
    fr: 'Japonais',
    pt: 'Japonês',
    ru: 'Японский',
    id: 'Bahasa Jepang',
    de: 'Japanisch',
    ja: '日本語',
    tr: 'Japonca',
    zh_hk: '日文',
    vi: 'Tiếng Nhật',
    ko: '일본어',
    it: 'Giapponese',
    th: 'ภาษาญี่ปุ่น',
    hi: 'जापानी',
    ur: 'جاپانی',
    ar: 'اليابانية'
  },
  tr: {
    en: 'Turkish',
    zh_cn: '土耳其语',
    es: 'Turco',
    fr: 'Turc',
    pt: 'Turco',
    ru: 'Турецкий',
    id: 'Bahasa Turki',
    de: 'Türkisch',
    ja: 'トルコ語',
    tr: 'Türkçe',
    zh_hk: '土耳其文',
    vi: 'Tiếng Thổ Nhĩ Kỳ',
    ko: '터키어',
    it: 'Turco',
    th: 'ภาษาตุรกี',
    hi: 'तुर्की',
    ur: 'ترکی',
    ar: 'التركية'
  },
  zh_hk: {
    en: 'Cantonese',
    zh_cn: '粤语',
    es: 'Cantonés',
    fr: 'Cantonais',
    pt: 'Cantonês',
    ru: 'Кантонский',
    id: 'Bahasa Kanton',
    de: 'Kantonesisch',
    ja: '広東語',
    tr: 'Kantonca',
    zh_hk: '廣東話',
    vi: 'Tiếng Quảng Đông',
    ko: '광둥어',
    it: 'Cantonese',
    th: 'ภาษากวางตุ้ง',
    hi: 'कैंटोनीज़',
    ur: 'کینٹونیز',
    ar: 'الكانتونية'
  },
  vi: {
    en: 'Vietnamese',
    zh_cn: '越南语',
    es: 'Vietnamita',
    fr: 'Vietnamien',
    pt: 'Vietnamita',
    ru: 'Вьетнамский',
    id: 'Bahasa Vietnam',
    de: 'Vietnamesisch',
    ja: 'ベトナム語',
    tr: 'Vietnamca',
    zh_hk: '越南文',
    vi: 'Tiếng Việt',
    ko: '베트남어',
    it: 'Vietnamita',
    th: 'ภาษาเวียดนาม',
    hi: 'वियतनामी',
    ur: 'ویتنامی',
    ar: 'الفيتنامية'
  },
  ko: {
    en: 'Korean',
    zh_cn: '韩语',
    es: 'Coreano',
    fr: 'Coréen',
    pt: 'Coreano',
    ru: 'Корейский',
    id: 'Bahasa Korea',
    de: 'Koreanisch',
    ja: '韓国語',
    tr: 'Korece',
    zh_hk: '韓文',
    vi: 'Tiếng Hàn',
    ko: '한국어',
    it: 'Coreano',
    th: 'ภาษาเกาหลี',
    hi: 'कोरियाई',
    ur: 'کوریائی',
    ar: 'الكورية'
  },
  it: {
    en: 'Italian',
    zh_cn: '意大利语',
    es: 'Italiano',
    fr: 'Italien',
    pt: 'Italiano',
    ru: 'Итальянский',
    id: 'Bahasa Italia',
    de: 'Italienisch',
    ja: 'イタリア語',
    tr: 'İtalyanca',
    zh_hk: '意大利文',
    vi: 'Tiếng Ý',
    ko: '이탈리아어',
    it: 'Italiano',
    th: 'ภาษาอิตาลี',
    hi: 'इतालवी',
    ur: 'اطالوی',
    ar: 'الإيطالية'
  },
  th: {
    en: 'Thai',
    zh_cn: '泰语',
    es: 'Tailandés',
    fr: 'Thaï',
    pt: 'Tailandês',
    ru: 'Тайский',
    id: 'Bahasa Thai',
    de: 'Thailändisch',
    ja: 'タイ語',
    tr: 'Tayca',
    zh_hk: '泰文',
    vi: 'Tiếng Thái',
    ko: '태국어',
    it: 'Tailandese',
    th: 'ภาษาไทย',
    hi: 'थाई',
    ur: 'تھائی',
    ar: 'التايلاندية'
  },
  hi: {
    en: 'Hindi',
    zh_cn: '印地语',
    es: 'Hindi',
    fr: 'Hindi',
    pt: 'Hindi',
    ru: 'Хинди',
    id: 'Bahasa Hindi',
    de: 'Hindi',
    ja: 'ヒンディー語',
    tr: 'Hintçe',
    zh_hk: '印地文',
    vi: 'Tiếng Hindi',
    ko: '힌디어',
    it: 'Hindi',
    th: 'ภาษาฮินดี',
    hi: 'हिन्दी',
    ur: 'ہندی',
    ar: 'الهندية'
  },
  ur: {
    en: 'Urdu',
    zh_cn: '乌尔都语',
    es: 'Urdu',
    fr: 'Ourdou',
    pt: 'Urdu',
    ru: 'Урду',
    id: 'Bahasa Urdu',
    de: 'Urdu',
    ja: 'ウルドゥー語',
    tr: 'Urduca',
    zh_hk: '烏爾都文',
    vi: 'Tiếng Urdu',
    ko: '우르두어',
    it: 'Urdu',
    th: 'ภาษาอูรดู',
    hi: 'उर्दू',
    ur: 'اردو',
    ar: 'الأردية'
  },
  ar: {
    en: 'Arabic',
    zh_cn: '阿拉伯语',
    es: 'Árabe',
    fr: 'Arabe',
    pt: 'Árabe',
    ru: 'Арабский',
    id: 'Bahasa Arab',
    de: 'Arabisch',
    ja: 'アラビア語',
    tr: 'Arapça',
    zh_hk: '阿拉伯文',
    vi: 'Tiếng Ả Rập',
    ko: '아랍어',
    it: 'Arabo',
    th: 'ภาษาอาหรับ',
    hi: 'अरबी',
    ur: 'عربی',
    ar: 'العربية'
  }
};

// Helper function to get language display info
export const getLanguageDisplay = (langCode) => {
  return LANGUAGES[langCode] || { name: langCode, flag: '🌍' };
};

// Helper function to get language name in a specific language
export const getLanguageName = (langCode, displayLang = 'en') => {
  return LANGUAGE_NAMES[langCode]?.[displayLang] || LANGUAGES[langCode]?.name || langCode;
};

export default LANGUAGES;
