'use strict';

// The Node side of the boundary generate-clip.js documents at its own top: text and a
// language in, one clip written to --out, a clean exit code, and nothing else load
// bearing on stdout or stderr. anki/addon/amgi_audio's test/test_generator.py proves the
// Python side of the same contract.
//
// `run()` is exercised here with a stubbed generator, never a real OpenAI client - there
// is no API key in this environment and live calls are not authorised. `main()`'s own
// argument handling and its "no key" failure are exercised too, since both return before
// ever requiring the `openai` package or touching the network.

const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { test } = require('node:test');

const { main, parseArgs, run } = require('../generate-clip');

function tempOutputPath() {
  return path.join(fs.mkdtempSync(path.join(os.tmpdir(), 'plusaudio-generate-clip-')), 'clip.mp3');
}

test('parseArgs collects the three flags and rejects an unknown one', () => {
  const options = parseArgs(['--text', '안녕', '--language', 'ko', '--out', '/tmp/x.mp3']);
  assert.deepEqual(options, { text: '안녕', language: 'ko', out: '/tmp/x.mp3' });

  assert.throws(() => parseArgs(['--bogus', 'x']), /unknown option --bogus/);
  assert.throws(() => parseArgs(['--text']), /--text needs a value/);
});

test('run() writes the generated bytes to --out and returns exit code 0', async () => {
  const out = tempOutputPath();
  const clip = Buffer.from([1, 2, 3, 4]);
  const calls = [];
  const generate = async (request) => {
    calls.push(request);
    return clip;
  };

  const code = await run({ text: 'hello', language: 'ko', out }, generate);

  assert.equal(code, 0);
  assert.deepEqual(calls, [{ text: 'hello', language: 'ko' }]);
  assert.deepEqual(fs.readFileSync(out), clip);
});

test('run() writes nothing and returns exit code 1 when generation fails', async () => {
  const out = tempOutputPath();
  const generate = async () => {
    throw new Error('Failed to generate valid audio for "hello" after 3 attempts');
  };

  const code = await run({ text: 'hello', language: 'ko', out }, generate);

  assert.equal(code, 1);
  assert.equal(fs.existsSync(out), false);
});

test('run() removes a stale clip left at --out by an earlier successful run', async () => {
  const out = tempOutputPath();
  fs.writeFileSync(out, Buffer.from('stale'));
  const generate = async () => {
    throw new Error('boom');
  };

  const code = await run({ text: 'hello', language: 'ko', out }, generate);

  assert.equal(code, 1);
  assert.equal(fs.existsSync(out), false);
});

test('main() returns exit code 2 and touches nothing when a required flag is missing', async () => {
  const out = tempOutputPath();
  const code = await main(['--text', 'hello', '--out', out]); // no --language
  assert.equal(code, 2);
  assert.equal(fs.existsSync(out), false);
});

test('main() returns exit code 1 with an actionable message when OPENAI_API_KEY is unset', async () => {
  const out = tempOutputPath();
  const previous = process.env.OPENAI_API_KEY;
  delete process.env.OPENAI_API_KEY;
  try {
    const code = await main(['--text', 'hello', '--language', 'ko', '--out', out]);
    assert.equal(code, 1);
    assert.equal(fs.existsSync(out), false);
  } finally {
    if (previous !== undefined) process.env.OPENAI_API_KEY = previous;
  }
});

test('main() prints usage and exits 0 on --help without requiring an API key', async () => {
  const previous = process.env.OPENAI_API_KEY;
  delete process.env.OPENAI_API_KEY;
  try {
    const code = await main(['--help']);
    assert.equal(code, 0);
  } finally {
    if (previous !== undefined) process.env.OPENAI_API_KEY = previous;
  }
});
